In [1]:
###importing library

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(2)

array([0.97338042, 0.92497249])

In [15]:
np.random.rand(3,3)

array([[0.6817756 , 0.16179737, 0.81314462],
       [0.67989949, 0.89379916, 0.93538945],
       [0.03464428, 0.11813461, 0.51671743]])

In [16]:
np.random.randint(0,100)

53

In [17]:
np.random.randint(0,100,5)

array([72, 74, 37, 47, 52])

In [18]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr=np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.shape

(25,)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr2=np.zeros(10)

In [24]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
arr2[:]=10

In [26]:
arr2

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [27]:
arr2=np.zeros((10,10))

In [28]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr2.shape[0]

10

In [30]:
1/0

ZeroDivisionError: division by zero

In [37]:
x=np.ones((5,5))

In [39]:
np.sum(x)

25.0